# Generated by Django 4.2.7 on 2023-11-17 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
