# Generated by Django 4.2.7 on 2023-11-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conta_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='agencia',
            field=models.CharField(max_length=4),
        ),
    ]
