# Generated by Django 4.2.7 on 2023-11-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_extrato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extrato',
        ),
    ]
