# Generated by Django 4.2.7 on 2023-12-01 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cartaocredito_conta_cartao_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local', models.CharField(max_length=255)),
                ('data_transacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('cartao_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cartaocredito')),
            ],
        ),
    ]
